<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TYULIKOVV7" tests="1" failures="1" timestamp="6 Jul 2017 14:15:05 GMT" time="10.378" errors="0">
  <testcase name="loginTest" time="3.575" classname="SimpleTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	3. Entry is displayed for observer	3. Entry is displayed for observer expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	3. Entry is displayed for observer	3. Entry is displayed for observer expected [false] but found [true]
	at SimpleTest.loginTest(SimpleTest.java:25)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite>
